
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos-store-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.8.0
          args:
          - "store"
          - "--log.level=debug"
          - "--data-dir=/data"
#          - "--objstore.config={type: GCS, config: {bucket: prometheus-long-term}}"
          - "--objstore.config-file=/etc/secret/thanos-store.yml"
          - "--index-cache-size=500MB"
          - "--chunk-pool-size=500MB"
#          env:
#            - name : GOOGLE_APPLICATION_CREDENTIALS
#              value: /etc/secret/thanos-gcs-credentials.json
          ports:
          - name: http
            containerPort: 10902
          - name: grpc
            containerPort: 10901
          livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          volumeMounts:
            - name: thanos-aws-credentials
              mountPath: /etc/secret
              readOnly: false
      volumes:
        - name: thanos-aws-credentials
          configMap:
            name: thanos-store-config
---